name: Publish to crates.io

on:
  push:
    branches:
      - master
    paths:
      - '.changeset/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract PR number
        id: pr
        run: |
          PR_NUMBER=$(git log -1 --pretty=%B | grep -oP '(?<=#)\d+' || echo "")
          echo "number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Bump version
        run: |
          nix run .#bump-version -- ${{ steps.pr.outputs.number }}

      - name: Get new version
        id: version
        run: echo "version=$(grep -m1 'version = ' Cargo.toml | cut -d'"' -f2)" >> $GITHUB_OUTPUT

      - name: Commit and push to current branch
        run: |
          git add .
          git commit -m "chore: bump version to ${{ steps.version.outputs.version }}"
          git push origin HEAD

      - name: Tag version
        run: |
          git tag "v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          nix run .#publish-crates

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          generate_release_notes: true
