name: Sync develop with master

on:
  workflow_run:
    workflows: ["Publish to crates.io"]
    types:
      - completed
    branches:
      - master

jobs:
  sync:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Setup SSH deploy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin git@github.com:fulsomenko/kanban.git

      - name: Merge master into develop
        run: |
          git fetch origin develop
          git checkout develop
          git merge origin/master -m "chore: sync develop with master after release [skip ci]"
          GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no" git push origin develop

      - name: Notify on failure
        if: failure()
        run: |
          echo "⚠️ Failed to sync develop with master"
          echo "Manual intervention may be required to resolve conflicts"
          echo "Run: git checkout develop && git merge master"
          exit 1
